# Site settings
title: Sketch Libraries
description: A Sketch App Libraries repository.
baseurl: "/skethlibraries.github.io" # the subpath of your site, e.g. /blog
url: "https://sketchlibraries.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: caiocall
user_description: Caio Calderari is a Designers
user_title: Caio Calderari
email: call@caiocall.com
twitter_username: caiocall
github_username:  caiocall
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
